version: '3'
services:
  neo4j:
    image: neo4j:3.3
    ports:
    - 7687:7687
    - 7474:7474
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs

  hamgraphs:
    image: hamgraphs/server:latest
    links:
      - "neo4j:database"
    depends_on:
      - neo4j
    ports:
    - 8080:8080
